# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit inequality.Rmd to modify this file

## ----setup, include = FALSE---------------------------------------------------
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE,
                      fig.align = "center", out.width = "100%")


## ----lorenz, fig.cap = "Lorenz curves for three synthetic income distributions with low, medium, and high inequality. Each series is a lognormal sample of 2000 observations. Distributions share the same geometric mean and differ only in dispersion. Dashed diagonal is the line of perfect equality. Each Gini is twice the area between its curve and the diagonal.", fig.alt = "A chart showing three Lorenz curves nested between the origin and the top-right corner of a square, alongside a dashed diagonal representing perfect equality. The innermost curve, close to the diagonal, corresponds to a Gini of 0.20; the middle curve to a Gini of 0.43; the outermost curve, furthest from the diagonal, to a Gini of 0.69. All three curves are monotonic and convex."----
knitr::include_graphics("figures/fig1_lorenz.pdf")


## ----gini-ci, fig.cap = "Mean 95 per cent Davidson bootstrap CI width for the Gini coefficient as a function of sample size. At each sample size the CI is computed on 40 independent lognormal draws (mu = 10.5, sigma = 0.8), each with 400 bootstrap replications. Sample sizes on the log scale. CI half-width falls by a factor of roughly six between n = 100 and n = 5000.", fig.alt = "A chart of confidence interval half-width on the vertical axis against sample size on a logarithmic horizontal axis. Values fall from above 0.05 at a sample size of 100 to below 0.02 at a sample size of 5000. The curve is smoothly decreasing and approximately linear in log space."----
knitr::include_graphics("figures/fig2_gini_ci.pdf")


## ----decompose, fig.cap = "Bourguignon between-within decomposition of Theil T across three grouping scenarios. Each scenario has 1500 observations in three groups with identical within-group dispersion (sigma = 0.6 lognormal) but different group-mean spread. Left bar: group means GBP 30k / 32k / 34k, between share 0.6 per cent. Middle bar: group means 25k / 35k / 55k. Right bar: group means 18k / 40k / 80k, between share 45 per cent. The between-within split is an immediate diagnostic for how much inequality is explained by the grouping variable.", fig.alt = "A stacked bar chart with three bars, each representing a different grouping scenario. Every bar is normalised to the same total height, representing the full Theil T index. The left bar is dominated by the within-group component (the between share is 0.6 per cent). The middle bar has a larger between-group share. The right bar is roughly evenly split, with the between-group share reaching 45 per cent."----
knitr::include_graphics("figures/fig3_decompose.pdf")


## ----gic, fig.cap = "Growth incidence curve on the package's synthetic panel dataset. Data from \\texttt{iq\\_sample\\_data(\"panel\")}: 1000 individuals across two periods, lognormal returns with heterogeneous growth (lower percentiles grow more slowly). Annualised growth rate at each 5-percentile bin is plotted against the base-period percentile rank. Dashed line is the mean annualised growth rate across the full distribution. The curve's upward slope signals inequality-increasing growth over the period.", fig.alt = "A line chart with the base-period percentile rank on the horizontal axis from 0 to 100 and the annualised growth rate on the vertical axis. The curve rises monotonically from a low value at the lowest percentile to a higher value at the top percentile. A horizontal dashed line marks the mean annualised growth rate; the curve is below the dashed line for lower percentiles and above it at higher percentiles."----
knitr::include_graphics("figures/fig4_gic.pdf")


## ----atkinson, fig.cap = "Atkinson index as a function of inequality-aversion parameter epsilon for two distributions. Blue solid: a single lognormal sample, n = 3000. Red dashed: a mixture, 85 per cent moderate lognormal plus 15 per cent high-mean high-variance lognormal, total n = 3000. At epsilon = 0.5 the two distributions score similarly; at epsilon = 2 the mixture distribution scores more than double the lognormal, reflecting the heavier top tail. The two distributions have Gini coefficients 0.41 and 0.56 respectively.", fig.alt = "A line chart with the inequality-aversion parameter epsilon on the horizontal axis from 0.1 to 2.5 and the Atkinson index value on the vertical axis. A solid blue line corresponds to a lognormal sample and rises gently. A dashed red line corresponds to a heavy-tailed mixture and rises much more steeply, reaching roughly double the blue line by epsilon equals 2."----
knitr::include_graphics("figures/fig5_atkinson.pdf")


## ----wb-gini, fig.cap = "Gini coefficient by country, 1970 to 2024, from the World Bank Poverty and Inequality Platform. Data: World Bank series \\texttt{SI.POV.GINI}, downloaded via the WDI API. Six economies with the longest continuous coverage are shown. Brazil shows the well-documented post-Bolsa-Familia decline from 58 in 1989 to 51 in 2024. The United States shows a steady rise from 37 in 1970 to 42 in 2024. Sweden, France, Germany cluster in the 25 to 32 band throughout. The United Kingdom traces a Thatcher-era rise and post-1990 stabilisation.", fig.alt = "A line chart with calendar year on the horizontal axis from 1970 to 2024 and Gini coefficient on the vertical axis from about 22 to 60. Six country series are plotted. Brazil sits well above the others, starting around 58 and declining to about 50. The United States climbs from 37 to 42. Sweden, France, and Germany cluster between 25 and 33 across the full period. The United Kingdom rises from 28 to 32 with most of the increase in the 1980s."----
knitr::include_graphics("figures/fig6_wb_gini.pdf")


## ----wb-summary---------------------------------------------------------------
wb_summary <- data.frame(
  Country = c("Sweden", "France", "United Kingdom", "Germany",
              "United States", "Brazil"),
  First = c(1975, 1970, 1970, 1991, 1970, 1981),
  `First Gini` = c(24.3, 37.1, 28.0, 29.3, 36.6, 57.9),
  Last = c(2023, 2023, 2021, 2022, 2024, 2024),
  `Last Gini` = c(29.3, 31.8, 32.4, 33.7, 41.8, 50.3),
  `Change (pp)` = c("+5.0", "-5.3", "+4.4", "+4.4", "+5.2", "-7.6"),
  check.names = FALSE
)
knitr::kable(
  wb_summary,
  caption = "First-year and last-year Gini plus total change for six countries in the World Bank Poverty and Inequality Platform panel. Ordered by latest observed Gini, ascending. Change is the last-year Gini minus the first-year Gini in percentage points.",
  booktabs = TRUE
)


## ----compare------------------------------------------------------------------
compare_tbl <- data.frame(
  Index = c("Gini", "Theil T (GE1)", "Theil L (GE0)",
            "Atkinson (e=0.5)", "Atkinson (e=1.0)",
            "Palma ratio", "Hoover", "P90/P10", "P80/P20"),
  Value = c(0.4300, 0.3307, 0.3241, 0.1506, 0.2768,
            2.1528, 0.3126, 7.8282, 3.9206)
)
knitr::kable(
  compare_tbl,
  caption = "Nine inequality and poverty indices for the package's synthetic income sample. Output of \\texttt{iq\\_compare(iq\\_sample\\_data(\"income\")\\$income)}. Gini and Theil agree on the total magnitude; Atkinson rises sharply with inequality aversion; Palma ratio captures the 10/40 tail concentration; P90/P10 gives the most intuitive read.",
  booktabs = TRUE,
  digits = 4
)

